@startuml
'https://plantuml.com/class-diagram

class Main
class Search

Main <|.. Search

class Search {
    +JsonReader JSONReader
    +String name
    +Double price
    +int quantity
    +String n
    {static} +productSearch()
}

class Main {
    +String firstLetter
    +String restOfLetters
    +Scanner start_scan
    +String product_name
    {static} +capitalize()
    {static} +main()
}

@enduml