@startuml
'https://plantuml.com/class-diagram

class Main
class Read

Main <|.. Read

class Read {
    {static} +int name_amount
    +File file_input
    +Scanner start_scan
    +ArrayList<String> array
    +String input_name
    {static} +reader()
}

class Main {
    +FileWriter fileWriter
    {static} +main()
}

@enduml