@startuml
'https://plantuml.com/class-diagram

class Main

class Main {
    {static} -int name_amount
    +File file_input
    +Scanner start_scan
    +ArrayList<String> array
    +String input_name

    +FileWriter fileWriter
    {static} +ArrayList<String> reader()
    {static} +void main()
}

@enduml