@startuml
'https://plantuml.com/class-diagram

class Main
class Histogram
Main <|-- Histogram

class Histogram {
    {static} +int word_length
    +LinkedHashMap<String, Integer> sortedWordFrequency
    {static} +organizeMap()
    {static} +histogramPrint()
}

class Main {
    +int word_length
    +Map<String, Integer> wordFrequency
    +File file_input
    +Scanner start_scan
    +String input_word
    +int frequencyCount
    {static} +main()
}

@enduml